version: '3.8'
services:
  app:
    build: .
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
    depends_on: []
